// vuejs/src/components/ResultList.vue
<template>
  <section>
    <template v-if="state.isLoading">
      <div v-for="n in 5" class="my-3" :key="n">
        <div class="my-1">
          <b-skeleton :animated="true"></b-skeleton>
        </div>
        <b-skeleton :animated="true"></b-skeleton>
        <b-skeleton :animated="true"></b-skeleton>
        <b-skeleton :animated="true" width="50%"></b-skeleton>
      </div>
    </template>
    <template v-else>
      <div class="my-3" v-for="result in state.results" :key="result.uniqueId">
        <div class="my-1">
          <a :href="result.clickUri">{{result.title}}</a>
        </div>
        <p>{{result.excerpt}}</p>
      </div>
    </template>
  </section>
</template>

<script>
import engine from "../Engine";
import { buildResultList } from "@coveo/headless";
export default {
  name: "ResultList",
  data: function () {
    return {
      state: {},
    };
  },
  created: function () {
    this.resultList = buildResultList(engine);
    this.resultList.subscribe(() => {
      this.state = { ...this.resultList.state };
    });
  },
};
</script>

// reactnative/components/ResultList.tsx
import React from 'react';
import {
  buildResultList,
  ResultList as HeadlessResultList,
  ResultListState,
} from '@coveo/headless';
import engine from '../app/Engine';
import {ScrollView} from 'react-native';
import {ListItem, Text} from 'react-native-elements';

const styles = {
  paddingVertical: 10,
};

export class ResultList extends React.Component<{}, ResultListState, null> {
  private headlessResultList: HeadlessResultList;
  private mounted = false;
  constructor(props: {}) {
    super(props);
    this.headlessResultList = buildResultList(engine);
    this.state = {
      isLoading: false,
      results: [],
    };
    this.headlessResultList.subscribe(() => {
      this.mounted && this.setState({...this.headlessResultList.state});
    });
  }

  componentDidMount() {
    this.mounted = true;
  }

  componentWillUnmount() {
    this.mounted = false;
  }

  render() {
    return (
      <ScrollView>
        {this.state.results.map((r) => {
          return (
            <ListItem key={r.uniqueId} bottomDivider={true} topDivider={true}>
              <ListItem.Content>
                <ListItem.Title>
                  {r.title}
                  {r.raw.date}
                </ListItem.Title>
                <Text style={styles}>{r.excerpt}</Text>
              </ListItem.Content>
            </ListItem>
          );
        })}
      </ScrollView>
    );
  }
}
