// reactnative/components/Summary.tsx
import React from 'react';
import {
  buildQuerySummary,
  QuerySummary,
  QuerySummaryState,
} from '@coveo/headless';
import {Text} from 'react-native';
import engine from '../app/Engine';

export class Summary extends React.Component<{}, QuerySummaryState> {
  private querySummary: QuerySummary;
  private mounted = false;
  constructor(props: {}) {
    super(props);
    this.querySummary = buildQuerySummary(engine);
    this.state = this.querySummary.state;
    this.querySummary.subscribe(() => {
      this.mounted && this.setState({...this.querySummary.state});
    });
  }

  componentDidMount() {
    this.mounted = true;
  }

  componentWillUnmount() {
    this.mounted = false;
  }

  render() {
    if (this.state.hasResults) {
      return (
        <Text>
          Results {this.state.firstResult}-{this.state.lastResult} of{' '}
          {this.state.total}
          {this.state.hasQuery ? ` for ${this.state.query}` : ''} in{' '}
          {this.state.durationInSeconds} seconds
        </Text>
      );
    }

    return <Text>No results</Text>;
  }
}

// vuejs/src/components/Summary.vue
<template>
  <section>
    <p
      v-if="summary.hasResults"
    >Results {{summary.firstResult}}-{{summary.lastResult}} of {{summary.total}} in {{summary.durationInSeconds}} seconds</p>
    <p v-else>No results for {{summary.query}}</p>
  </section>
</template>
<script>
import { buildQuerySummary } from "@coveo/headless";
import engine from "../Engine";
export default {
  name: "Summary",
  data: function () {
    return {
      summary: {},
    };
  },
  created: function () {
    this.querySummary = buildQuerySummary(engine);
    this.querySummary.subscribe(() => {
      this.summary = { ...this.querySummary.state };
    });
  },
};
</script>
